### ISSUE TITLE
Dislike a Post

### ISSUE THREAD

**Issue by adyassine** [webtions/i-recommend-this#3] opened 2015-08-27 07:07 UTC
Can we dislike a post ?

**Comment by hchouhan** [comment] 2015-08-27 16:22
Hello, As of now that is not possible. But I might look into it in the future.

**Comment by hchouhan** [comment] 2021-12-30 08:51
Duplicate of https://github.com/webtions/i-recommend-this/issues/8.

**Closed by hchouhan** 2021-12-30 08:51 UTC
Labels: Feature Request
